[package]
name = 'calculator_l05'
version = '1.0.0'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "testnet" }

[addresses]
metaschool = "0xe28a2ea62398afc878e75b4c1492acd0fb240bb22ad3cabdd7f6baf06cc407c7"
std = "0x1"